version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tracline-postgres
    environment:
      # These values come from .env file or use defaults
      POSTGRES_DB: ${POSTGRES_DB:-tracline}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      # Map host port to container port 5432
      - "${DB_PORT:-5432}:5432"
    volumes:
      # Persist data between container restarts
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Check if PostgreSQL is ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-tracline}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - tracline-network

  # Optional: pgAdmin for database management (uncomment to enable)
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: tracline-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@tracline.local
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  #   networks:
  #     - tracline-network

volumes:
  postgres_data:
    name: tracline_postgres_data

networks:
  tracline-network:
    name: tracline_network
    driver: bridge